alter table ACCOUNTING_PK_MOVING_ENTITY add constraint FK_ACCOUNTING_PK_MOVING_ENTITY_ON_PK_ENTITY foreign key (PK_ENTITY_ID) references ACCOUNTING_PK_ENTITY(ID) on delete SET NULL;
create index IDX_ACCOUNTING_PK_MOVING_ENTITY_ON_PK_ENTITY on ACCOUNTING_PK_MOVING_ENTITY (PK_ENTITY_ID);
