alter table ACCOUNTING_PK_ENTITY add constraint FK_ACCOUNTING_PK_ENTITY_ON_CPU foreign key (CPU_ID) references ACCOUNTING_CPU_ENTITY(ID);
create index IDX_ACCOUNTING_PK_ENTITY_ON_CPU on ACCOUNTING_PK_ENTITY (CPU_ID);
