alter table ACCOUNTING_PK_ENTITY drop column VERSION_BIOS__U04905 cascade ;
alter table ACCOUNTING_PK_ENTITY drop column MOTHERBOARD_MANUFACTURER__U61262 cascade ;
alter table ACCOUNTING_PK_ENTITY drop column MOTHERBOARD_SERIAL_NUMBER__U23069 cascade ;
alter table ACCOUNTING_PK_ENTITY drop column SERIAL_NUMBER_PK__U44513 cascade ;
