alter table ACCOUNTING_PK_ENTITY add constraint FK_ACCOUNTING_PK_ENTITY_ON_PK_MOVING foreign key (PK_MOVING_ID) references ACCOUNTING_PK_MOVING_ENTITY(ID) on delete CASCADE;
create index IDX_ACCOUNTING_PK_ENTITY_ON_PK_MOVING on ACCOUNTING_PK_ENTITY (PK_MOVING_ID);
