alter table ACCOUNTING_PK_ENTITY change column CPU_ID CPU_ID__U58623 bigint^
drop index IDX_ACCOUNTING_PK_ENTITY_ON_CPU on ACCOUNTING_PK_ENTITY ;
alter table ACCOUNTING_PK_ENTITY drop foreign key FK_ACCOUNTING_PK_ENTITY_ON_CPU;
